import { z } from 'zod';
export declare const GetTranscriptResource = "/get-transcript";
export declare const GetTranscriptRequestSchema: z.ZodObject<{
    sessionToken: z.ZodString;
    transcriptId: z.ZodString;
}, "strip", z.ZodTypeAny, {
    transcriptId: string;
    sessionToken: string;
}, {
    transcriptId: string;
    sessionToken: string;
}>;
export declare const GetTranscriptResponseSchema: z.ZodObject<{
    transcriptId: z.ZodString;
    accountEmail: z.ZodString;
    isK12: z.ZodNumber;
    schoolName: z.ZodString;
    schoolAddress: z.ZodString;
    adminTitle: z.ZodString;
    adminName: z.ZodString;
    adminPhone: z.ZodString;
    adminEmail: z.ZodString;
    studentNameFirst: z.ZodString;
    studentNameMiddle: z.ZodString;
    studentNameLast: z.ZodString;
    studentNameSuffix: z.ZodString;
    studentBirthDate: z.ZodString;
    studentGraduationDate: z.ZodString;
    studentAddress: z.ZodString;
    studentPhone: z.ZodString;
    studentEmail: z.ZodString;
    transcriptTitle: z.ZodString;
    transcriptLogo: z.ZodString;
    arrangeByGrade: z.ZodNumber;
    computeWeightedGPA: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    transcriptId: string;
    accountEmail: string;
    isK12: number;
    schoolName: string;
    schoolAddress: string;
    adminTitle: string;
    adminName: string;
    adminPhone: string;
    adminEmail: string;
    studentNameFirst: string;
    studentNameMiddle: string;
    studentNameLast: string;
    studentNameSuffix: string;
    studentBirthDate: string;
    studentGraduationDate: string;
    studentAddress: string;
    studentPhone: string;
    studentEmail: string;
    transcriptTitle: string;
    transcriptLogo: string;
    arrangeByGrade: number;
    computeWeightedGPA: number;
}, {
    transcriptId: string;
    accountEmail: string;
    isK12: number;
    schoolName: string;
    schoolAddress: string;
    adminTitle: string;
    adminName: string;
    adminPhone: string;
    adminEmail: string;
    studentNameFirst: string;
    studentNameMiddle: string;
    studentNameLast: string;
    studentNameSuffix: string;
    studentBirthDate: string;
    studentGraduationDate: string;
    studentAddress: string;
    studentPhone: string;
    studentEmail: string;
    transcriptTitle: string;
    transcriptLogo: string;
    arrangeByGrade: number;
    computeWeightedGPA: number;
}>;
export type GetTranscriptRequest = z.infer<typeof GetTranscriptRequestSchema>;
export type GetTranscriptResponse = z.infer<typeof GetTranscriptResponseSchema>;
